### PR TITLE
Create secrets_test.json

### PR DESCRIPTION
**Pull request by xdayaan**

### CODE REVIEW

**Comment by SahilSikarwar** [comment]
Secrets Caught!

/home/ubuntu/shiftLeftSecurity/repoScan/tewari111/hello-world/secrets_test.json#L5
/home/ubuntu/shiftLeftSecurity/repoScan/tewari111/hello-world/secrets_test.json#L0

**Comment by SahilSikarwar** [comment]
Secrets Caught!

https://raw.githubusercontent.com/tewari111/hello-world/test/secrets_test.json#L5
https://raw.githubusercontent.com/tewari111/hello-world/test/secrets_test.json#L0

**Comment by xdayaan** [comment]
Secrets were caught during scan

**Comment by xdayaan** [comment]
Secrets were caught during scan

**Comment by xdayaan** [comment]
Warning! 3 secrets and 18 vulnerabilities found in the PR.

**Pull request closed without merging**
